
# mongodb_to_mssql_config.yaml
# Sample configuration for MongoDB to MSSQL ETL pipeline

# Data source configuration
source:
  type: mongodb
  mongodb:
    host: "localhost"
    port: 27017
    database: "source_database"
    collection: "customers"
    username: null
    password: null
    query: {}  # Empty query means get all documents
    limit: 0   # 0 means no limit
  parser:
    convert_objectid: true
    convert_datetime: true
    preserve_id_field: true

# Data target configuration
target:
  type: mssql
  mssql:
    server: "localhost"
    database: "etl_target_db"
    table_name: "processed_customers"
    username: "sa"
    password: "YourPassword123"
    port: 1433
    batch_size: 500
    create_table: true
    truncate_before_load: false
    upsert_mode: true
    primary_key: "customer_id"

# Transformations for MongoDB data
transformations:
  data_cleaner:
    enabled: true
    config:
      cleaning_rules:
        trim_whitespace: true
        remove_empty_strings: true
        standardize_nulls: true
        validate_emails: true
        clean_phone_numbers: false
      strict_validation: false

  flattener:
    enabled: true
    config:
      separator: "_"
      max_depth: 5
      array_handling: "concat"
      preserve_arrays: false

  field_mapper:
    enabled: true
    config:
      field_mappings:
        mongodb:
          customer_id: ["_id"]
          full_name: ["customer_name", "name", "fullName"]
          email_address: ["electronic_mail", "email", "emailAddress"]
          phone_number: ["mobile", "phone", "phoneNumber"]
          customer_age: ["age", "customer_age"]
          account_balance: ["balance", "account_balance"]
          registration_date: ["created_date", "registration_date"]
          is_premium_member: ["is_premium", "premium", "isPremium"]
      keep_unmapped_fields: true
      case_sensitive: false

  type_converter:
    enabled: true
    config:
      type_conversions:
        customer_age: "int"
        account_balance: "float"
        is_premium_member: "bool"
        registration_date: "datetime"
        full_name: "str"
        email_address: "str"
      strict_mode: false

  metadata_enricher:
    enabled: true
    config:
      add_created_at: true
      add_processed_at: true
      add_unique_id: false  # We already have customer_id
      add_source_info: true
      created_at_field: "createdAt"
      additional_metadata:
        pipeline_version: "1.0.0"
        environment: "production"
        data_source: "mongodb_customers"

# Pipeline configuration
pipeline:
  name: "MongoDB to MSSQL Customer ETL"
  description: "ETL pipeline for processing customer data from MongoDB to MSSQL"
  version: "1.0.0"
  logging_level: "INFO"